import NavBar from "@/components/_pages/landing/NavBar";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="pb-20">
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
